### ISSUE TITLE
Timecapsule and Looper usage instructions/manuals

### ISSUE THREAD

**Issue by hellocatfood** [OpenMusicKontrollers/orbit.lv2#1]
I've been looking for a midi looper and came across Timecapsule and Looper. I've compiled them and loaded them into Carla but can't figure out how to use them. Are there usage instructions for these and other plugins?

**Comment by hellocatfood** [comment]
I just compiled from gitlab (and tried github as well) and it seems some of the options, in particular `looper_play_capacity`, `looper_rec_capacity` are not being shown

![Screenshot from 2020-08-24 22-53-41](https://user-images.githubusercontent.com/151947/91100378-00eb7780-e65d-11ea-9bea-52f9a9bb7444.png)

**Comment by ventosus** [comment]
Those are read-only output parameters (you can't change them). Carla seems not to show them, so that's the host's problem, the plugin is fine.
